apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ser2net.fullname" . }}
  labels:
{{ include "ser2net.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ser2net.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "ser2net.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.shellCmd }}
          command: ["/bin/sh"]
          args: ["-c", '{{ .Values.shellCmd }}']
          {{- end }}
          securityContext:
            privileged: true
          volumeMounts:
            - name: config-volume
              mountPath: "/etc/ser2net.conf"
              subPath: "ser2net.conf"
            - mountPath: {{ .Values.device.mountPath }}
              name: device
          ports:
            - name: ser2net
              containerPort: 3333
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "ser2net.fullname" . }}
            items:
             - key: "ser2net.conf"
               path: "ser2net.conf"
        - name: device
          hostPath:
            path: {{ .Values.device.hostPath }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
