apiVersion: v1
kind: Service
metadata:
  name: {{ include "ser2net.fullname" . }}
  labels:
{{ include "ser2net.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: ser2net
      protocol: TCP
      name: ser2net
  selector:
    app.kubernetes.io/name: {{ include "ser2net.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
